// <auto-generated />
namespace Fabrica.Carros.Dados.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AdicaoCarrosOK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdicaoCarrosOK));
        
        string IMigrationMetadata.Id
        {
            get { return "202012032343061_AdicaoCarrosOK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
